apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cirda.fullname" . }}-secret
  labels:
    {{- include "cirda.labels" . | nindent 4 }}
type: Opaque
stringData:
  CIRDA_DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  CIRDA_REDIS_URL: {{ .Values.secrets.redisUrl | quote }}
  CIRDA_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  CIRDA_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.secrets.kafkaBootstrapServers | quote }}
